pipeline {
    agent any
    tools { 
        maven 'Default' 
        jdk 'Default' 
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}
